src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    return view('welcome');
    return redirect( '/home' );
});

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::middleware(['auth'])->group(function () {
    Route::resource('users', 'UsersController');
});

Route::middleware(['auth', 'apikey'])->group(function () {

    Route::get('/mail_settings', function () {
        return view( 'email_settings' );
    });
    Route::post('/mail_settings', 'HomeController@test')->name('smtp_update');
    Route::get('/test_mail_settings','HomeController@checkSMTP')->name('test_mail_settings');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('stores', 'StoresController');
    Route::any('/stores/list', 'StoresController@storeList')->name('stores.list');
    Route::get('/stores/fields/{id?}', 'StoresController@fields')->name('stores.fields');

    Route::resource('orders', 'OrdersController');
    Route::post('/orders/list/{store_id?}', 'OrdersController@orderList')->name('orders.list');
    Route::post('/orders/statuses/{store_id?}', 'OrdersController@statuses')->name('orders.statuses');
    Route::get('/orders/{store_id?}/{order_id?}', 'OrdersController@orderInfo')->name('orders.info');
    Route::get('/orders/{store_id?}/{order_id?}/products', 'OrdersController@orderProducts')->name('orders.products');
    Route::post('/orders/abandoned/{store_id?}', 'OrdersController@abandoned')->name('orders.abandoned');

    Route::get('/products', 'ProductsController@index')->name('products.index');
    Route::post('/products/list/{store_id?}', 'ProductsController@productList')->name('products.list');
    Route::delete('/products/{store_id?}/{product_id?}', 'ProductsController@destroy')->name('products.delete');
    Route::get('/products/{store_id?}/{product_id?}/edit', 'ProductsController@edit')->name('products.edit');
    Route::post('/products/{store_id?}/{product_id?}', 'ProductsController@update')->name('products.update');
    Route::post('/products/{store_id?}/{product_id?}/delete_image', 'ProductsController@destroyImage')->name('products.deleteImage');

    Route::get('/customers', 'CustomersController@index')->name('customers.index');
    Route::post('/customers/list/{store_id?}', 'CustomersController@customerList')->name('customers.list');
    Route::post('/subscribers/list/{store_id?}', 'CustomersController@subscriberList')->name('subscribers.list');

    Route::get('/categories', 'CategoriesController@index')->name('categories.index');
    Route::post('/categories/list/{store_id?}', 'CategoriesController@categoryList')->name('categories.list');
    Route::get('/categories/{store_id?}/{category_id?}/edit', 'CategoriesController@edit')->name('categories.edit');
    Route::post('/categories/{store_id?}/{category_id?}', 'CategoriesController@update')->name('categories.update');
    Route::delete('/categories/{store_id?}/{category_id?}', 'CategoriesController@destroy')->name('categories.delete');

    Route::any('businessCases', function (){
        return redirect( '/home' );
    });

    Route::prefix('businessCases')
        ->name('businessCases.')
        ->middleware(['checkSMTP'])
        ->group(function () {

        Route::get('import_orders_automation', 'BusinessCases\ImportOrdersAutomationController@index' )->name('import_orders_automation');

        Route::get('automatic_email_sending', 'BusinessCases\AutomaticEmailSendingController@index' )->name('automatic_email_sending');
        Route::post('automatic_email_sending/compose', 'BusinessCases\AutomaticEmailSendingController@compose')->name('automatic_email_sending.compose');
        Route::post('automatic_email_sending/send', 'BusinessCases\AutomaticEmailSendingController@send')->name('automatic_email_sending.send');

        Route::get('abandoned_cart_recovery', 'BusinessCases\AbandonedCartRecoveryController@index' )->name('abandoned_cart_recovery');
        Route::post('abandoned_cart_recovery/compose', 'BusinessCases\AbandonedCartRecoveryController@compose')->name('abandoned_cart_recovery.compose');
        Route::post('abandoned_cart_recovery/send', 'BusinessCases\AbandonedCartRecoveryController@send')->name('abandoned_cart_recovery.send');

        Route::get('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@index")->name('automatic_price_updating');
        Route::get('automatic_price_updating/create', "BusinessCases\AutomaticPriceUpdatingController@create")->name('automatic_price_updating.create');
        Route::get('automatic_price_updating/edit', "BusinessCases\AutomaticPriceUpdatingController@edit")->name('automatic_price_updating.edit');
        Route::post('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@store")->name('automatic_price_updating.store');
        Route::put('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@update")->name('automatic_price_updating.update');
        Route::get('automatic_price_updating/products', "BusinessCases\AutomaticPriceUpdatingController@products")->name('automatic_price_updating.products');

    });



});

src/resources/views/parts/footer.blade.php
<footer class="footer mt-auto py-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="footer-widgets" style="font-size: 13px;">
                    <div class="row">
                        <div class="col-md-3 text-center" data-motopress-type="dynamic-sidebar"
                             data-motopress-sidebar-id="footer-sidebar-5">
                            <div id="text-6" class="visible-all-devices twitter-widget"><h6>Latest whitepaper</h6>
                                <div class="textwidget"><a
                                            href="https://www.api2cart.com/resources/how-to-market-your-integration/"
                                            target="_blank"><img
                                                src="https://app.api2cart.com/images/how-to-market-your-integration-1.png"
                                                style="max-height: 180px;"></a></div>
                            </div>
                        </div>
                        <div class="col-md-2" data-motopress-type="dynamic-sidebar" data-motopress-sidebar-id="footer-sidebar-1">
                            <div id="nav_menu-3" class="visible-all-devices "><h6>Getting started</h6><div class="menu-started-container"><ul id="menu-started" class="menu">
                                        <li id="menu-item-2664" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2664"><a href="https://www.api2cart.com/pricing/">Pricing</a></li>
                                        <li id="menu-item-573" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-573"><a href="https://www.api2cart.com/use-cases/">Use Cases</a></li>
                                        <li id="menu-item-917" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-917"><a href="https://www.api2cart.com/supported-api-methods/">Supported Methods</a></li>
                                        <li id="menu-item-941" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-941"><a href="https://www.api2cart.com/supported-platforms/">Supported Platforms</a></li>
                                    </ul></div></div>    </div>
                        <div class="col-md-2" data-motopress-type="dynamic-sidebar" data-motopress-sidebar-id="footer-sidebar-2">
                            <div id="nav_menu-3" class="visible-all-devices "><h6>Information</h6><div class="menu-information-container"><ul id="menu-information" class="menu"><li id="menu-item-576" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-576"><a href="https://www.api2cart.com/blog/">Blog</a></li>
                                        <li id="menu-item-2664" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2664"><a href="https://www.api2cart.com/resources/">Resources</a></li>
                                        <li id="menu-item-573" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-573"><a href="https://www.api2cart.com/clients/">Clients</a></li>
                                        <li id="menu-item-1371" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1371"><a href="https://www.api2cart.com/testimonials/">Testimonials</a></li>
                                        <li id="menu-item-6607" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6607"><a href="https://www.api2cart.com/integration-partner/">Integration Partners</a></li>
                                        <li id="menu-item-919" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-919"><a href="https://www.api2cart.com/contact-us/">Contact Us</a></li>
                                    </ul></div></div>    </div>
                        <div class="col-md-2" data-motopress-type="dynamic-sidebar" data-motopress-sidebar-id="footer-sidebar-3">
                            <div id="nav_menu-4"><h6>Developer Resources</h6><div class="menu-developer-resources-container"><ul id="menu-developer-resources" class="menu"><li id="menu-item-195" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-195"><a href="http://docs.api2cart.com/?__hstc=161438946.3284b993e621b0e87ef49d650bf3a825.1475060720349.1475148454578.1475167183155.6&amp;__hssc=161438946.2.1475167183155&amp;__hsfp=938662876">API Documentation</a></li>
                                        <li id="menu-item-100" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-100"><a href="http://docs.api2cart.com/post/interactive-docs?__hstc=161438946.3284b993e621b0e87ef49d650bf3a825.1475060720349.1475148454578.1475167183155.6&amp;__hssc=161438946.2.1475167183155&amp;__hsfp=938662876">Interactive Demo</a></li>
                                        <li id="menu-item-194" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-194"><a href="http://docs.api2cart.com/post/integration-code-samples?__hstc=161438946.3284b993e621b0e87ef49d650bf3a825.1475060720349.1475148454578.1475167183155.6&amp;__hssc=161438946.2.1475167183155&amp;__hsfp=938662876">Code Samples</a></li>
                                        <li id="menu-item-2665" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2665"><a href="https://www.api2cart.com/release-notes/">Release Notes</a></li>
                                    </ul></div></div>    </div>
                        <div class="col-md-3" data-motopress-type="dynamic-sidebar" data-motopress-sidebar-id="footer-sidebar-4">
                            <div id="nav_menu-6" class="visible-all-devices "><h6>Support</h6><div class="menu-support-container"><ul id="menu-support" class="menu"><li id="menu-item-918" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-918"><a href="https://www.api2cart.com/faqs/">FAQs</a></li>
                                        <!--                              <li id="menu-item-200" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-200"><a target="_blank" href="http://support.magneticone.com/index.php?/Tickets/Submit/RenderForm/45&amp;__hstc=161438946.3284b993e621b0e87ef49d650bf3a825.1475060720349.1475148454578.1475167183155.6&amp;__hssc=161438946.2.1475167183155&amp;__hsfp=938662876">Submit a Ticket</a></li>-->
                                        <li id="menu-item-201" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-201"><a target="_blank" href="http://ideas.api2cart.com/?__hstc=161438946.3284b993e621b0e87ef49d650bf3a825.1475060720349.1475148454578.1475167183155.6&amp;__hssc=161438946.2.1475167183155&amp;__hsfp=938662876">Submit a Feature</a></li>
                                        <li id="menu-item-1368" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1368"><a href="https://www.api2cart.com/service-level-agreement/">Service Level Agreement</a></li>
                                        <li id="menu-item-1369" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1369"><a href="https://www.api2cart.com/terms-service/">Terms of Service</a></li>
                                        <li id="menu-item-1370" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1370"><a href="https://www.api2cart.com/privacy-policy/">Privacy Policy</a></li>
                                    </ul></div></div>    </div>
                    </div>
                </div>
                <div class="col-md-12 text-center text-muted">
                    <div class="copyright" >
                        <div id="footer-text" class="footer-text">
                            <div><span>&#169; 2020</span> MagneticOne</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

src/resources/views/parts/messages.blade.php
@if ($message = Session::get('success'))

    <div class="alert alert-success alert-block" >

        <button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

    </div>

@endif



@if ($message = Session::get('error'))

    <div class="alert alert-danger alert-block" >

        <button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

    </div>

@endif



@if ($message = Session::get('warning'))

    <div class="alert alert-warning alert-block" >

        <button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

    </div>

@endif



@if ($message = Session::get('info'))

    <div class="alert alert-info alert-block" >

        <button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

    </div>

@endif



@if ($errors->any())

    <div class="alert alert-danger" >

        <button type="button" class="close" data-dismiss="alert">×</button>

        Please check the form below for errors

    </div>

@endif

<script type="text/javascript">
    $(".alert").delay(4000).slideUp(200, function() {
        $(this).alert('close');
    });
</script>

src/resources/views/parts/sidebar.blade.php
<div class="col-lg-2">
    <div class="card">
        <div class="card-header">
            Entities
        </div>

        <div class="card-body sidemenu">
            <ul class="nav flex-column">
                <li class="nav-item" >
                    <a href="{{ url('/home') }}" class="nav-link {{ (request()->is('home')) ? 'active' : '' }}">
                        Dashboard
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="{{ route('stores.index') }}" class="nav-link {{ (request()->is('stores') || request()->is('stores/*')) ? 'active' : '' }}">
                        Stores
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="{{ route('orders.index') }}" class="nav-link {{ (request()->is('orders') || request()->is('orders/*')) ? 'active' : '' }}">
                        Orders
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="{{ route('customers.index') }}" class="nav-link {{ (request()->is('customers') || request()->is('customers/*')) ? 'active' : '' }}">
                        Customers
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="{{ route('products.index') }}" class="nav-link {{ (request()->is('products') || request()->is('products/*')) ? 'active' : '' }}">
                        Products
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="{{ route('categories.index') }}" class="nav-link {{ (request()->is('categories') || request()->is('categories/*')) ? 'active' : '' }}">
                        Categories
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-header">
            Business Cases
        </div>

        <div class="card-body sidemenu">
            <ul class="nav flex-column">
                <li class="nav-item" >
                    <a href="{{ route('businessCases.import_orders_automation') }}" class="nav-link {{ (request()->is('businessCases/import_orders_automation') || request()->is('businessCases/import_orders_automation/*')) ? 'active' : '' }}">
                        Import Orders Automation
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="{{ route('businessCases.abandoned_cart_recovery') }}" class="nav-link {{ (request()->is('businessCases/abandoned_cart_recovery') || request()->is('businessCases/abandoned_cart_recovery/*')) ? 'active' : '' }}">
                        Abandoned cart recovery
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="{{ route('businessCases.automatic_price_updating') }}" class="nav-link {{ (request()->is('businessCases/automatic_price_updating') || request()->is('businessCases/automatic_price_updating/*')) ? 'active' : '' }} ">
                        Automatic Price Updating
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="{{ route('businessCases.automatic_email_sending') }}" class="nav-link  {{ (request()->is('businessCases/automatic_email_sending') || request()->is('businessCases/automatic_email_sending/*')) ? 'active' : '' }}">
                        Automatic Email Sending
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="#" class="nav-link disabled ">
                        Automatic Synchronization of Inventory
                    </a>
                </li>
                <li class="nav-item" >
                    <a href="https://api2cart.com/business-cases" target="_blank" class="nav-link">
                        More Cases
                    </a>
                </li>
            </ul>
        </div>
    </div>

</div>