src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    return view('welcome');
    return redirect( '/home' );
});

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::middleware(['auth'])->group(function () {
    Route::resource('users', 'UsersController');
});

Route::middleware(['auth', 'apikey'])->group(function () {

    Route::get('/mail_settings', function () {
        return view( 'email_settings' );
    });
    Route::post('/mail_settings', 'HomeController@test')->name('smtp_update');
    Route::get('/test_mail_settings','HomeController@checkSMTP')->name('test_mail_settings');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('stores', 'StoresController');
    Route::any('/stores/list', 'StoresController@storeList')->name('stores.list');
    Route::get('/stores/fields/{id?}', 'StoresController@fields')->name('stores.fields');

    Route::resource('orders', 'OrdersController');
    Route::post('/orders/list/{store_id?}', 'OrdersController@orderList')->name('orders.list');
    Route::post('/orders/statuses/{store_id?}', 'OrdersController@statuses')->name('orders.statuses');
    Route::get('/orders/{store_id?}/{order_id?}', 'OrdersController@orderInfo')->name('orders.info');
    Route::get('/orders/{store_id?}/{order_id?}/products', 'OrdersController@orderProducts')->name('orders.products');
    Route::post('/orders/abandoned/{store_id?}', 'OrdersController@abandoned')->name('orders.abandoned');

    Route::get('/products', 'ProductsController@index')->name('products.index');
    Route::post('/products/list/{store_id?}', 'ProductsController@productList')->name('products.list');
    Route::delete('/products/{store_id?}/{product_id?}', 'ProductsController@destroy')->name('products.delete');
    Route::get('/products/{store_id?}/{product_id?}/edit', 'ProductsController@edit')->name('products.edit');
    Route::post('/products/{store_id?}/{product_id?}', 'ProductsController@update')->name('products.update');
    Route::post('/products/{store_id?}/{product_id?}/delete_image', 'ProductsController@destroyImage')->name('products.deleteImage');

    Route::get('/customers', 'CustomersController@index')->name('customers.index');
    Route::post('/customers/list/{store_id?}', 'CustomersController@customerList')->name('customers.list');
    Route::post('/subscribers/list/{store_id?}', 'CustomersController@subscriberList')->name('subscribers.list');

    Route::get('/categories', 'CategoriesController@index')->name('categories.index');
    Route::post('/categories/list/{store_id?}', 'CategoriesController@categoryList')->name('categories.list');
    Route::get('/categories/{store_id?}/{category_id?}/edit', 'CategoriesController@edit')->name('categories.edit');
    Route::post('/categories/{store_id?}/{category_id?}', 'CategoriesController@update')->name('categories.update');
    Route::delete('/categories/{store_id?}/{category_id?}', 'CategoriesController@destroy')->name('categories.delete');

    Route::any('businessCases', function (){
        return redirect( '/home' );
    });

    Route::prefix('businessCases')
        ->name('businessCases.')
        ->middleware(['checkSMTP'])
        ->group(function () {

        Route::get('import_orders_automation', 'BusinessCases\ImportOrdersAutomationController@index' )->name('import_orders_automation');

        Route::get('automatic_email_sending', 'BusinessCases\AutomaticEmailSendingController@index' )->name('automatic_email_sending');
        Route::post('automatic_email_sending/compose', 'BusinessCases\AutomaticEmailSendingController@compose')->name('automatic_email_sending.compose');
        Route::post('automatic_email_sending/send', 'BusinessCases\AutomaticEmailSendingController@send')->name('automatic_email_sending.send');

        Route::get('abandoned_cart_recovery', 'BusinessCases\AbandonedCartRecoveryController@index' )->name('abandoned_cart_recovery');
        Route::post('abandoned_cart_recovery/compose', 'BusinessCases\AbandonedCartRecoveryController@compose')->name('abandoned_cart_recovery.compose');
        Route::post('abandoned_cart_recovery/send', 'BusinessCases\AbandonedCartRecoveryController@send')->name('abandoned_cart_recovery.send');

        Route::get('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@index")->name('automatic_price_updating');
        Route::get('automatic_price_updating/create', "BusinessCases\AutomaticPriceUpdatingController@create")->name('automatic_price_updating.create');
        Route::get('automatic_price_updating/edit', "BusinessCases\AutomaticPriceUpdatingController@edit")->name('automatic_price_updating.edit');
        Route::post('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@store")->name('automatic_price_updating.store');
        Route::put('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@update")->name('automatic_price_updating.update');
        Route::get('automatic_price_updating/products', "BusinessCases\AutomaticPriceUpdatingController@products")->name('automatic_price_updating.products');

    });



});

src/app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OrderRequest;
use App\Services\Api2Cart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class OrdersController extends Controller
{

    private $api2cart;


    public function __construct(Api2Cart $api2Cart)
    {
        $this->api2cart = $api2Cart;
    }

    public function index()
    {
        return view('orders.index');
    }

    public function orderList($store_id=null,Request $request)
    {
        \Debugbar::disable();


        /**
         * get account carts & extract exact store info
         */
        $carts = collect($this->api2cart->getCartList());
        $storeInfo = $carts->where('store_key', $store_id)->first();

        $sort_by      = ($request->get('sort_by')) ? $request->get('sort_by') : null;
        $sort_direct  = ($request->get('sort_direct')) ? true : false;
        $created_from = ($request->get('created_from')) ? $request->get('created_from') : null;
        $limit        = ($request->get('limit')) ? $request->get('limit') : null;

        $totalOrders = $this->api2cart->getOrderCount( $store_id );

        $orders = collect([]);


        if ( $totalOrders ){

            $result = $this->api2cart->getOrderList( $store_id, null, null, null, $created_from );

            $newOrders = (isset($result['result']['orders_count'])) ? collect( $result['result']['order'] ) : collect([]);
            // put additional information
            if ( $newOrders->count() ){
                foreach ($newOrders as $item){
                    $newItem = $item;
                    $newItem['cart_id'] = $storeInfo['cart_id'];
                    $orders->push( $newItem );
                }
            }


            if ( isset($result['pagination']['next']) && strlen($result['pagination']['next']) ){
                // get next iteration to load rest orders
                while( isset($result['pagination']['next']) && strlen($result['pagination']['next']) ){
                    $result = $this->api2cart->getOrderListPage( $store_id , $result['pagination']['next']);
                    $newOrders = (isset($result['result']['orders_count'])) ? collect( $result['result']['order'] ) : collect([]);
                    // put additional information
                    if ( $newOrders->count() ){
                        foreach ($newOrders as $item){
                            $newItem = $item;
                            $newItem['cart_id'] = $storeInfo['cart_id'];
                            $orders->push( $newItem );
                        }
                    }
                }

            }


        }

//        $result = $this->api2cart->getOrderList( $store_id , 'create_at.value', null,$limit);
//        Log::debug('raw api result');
//        Log::debug( print_r($result,1) );

        if ( $sort_by  ){
            switch ($sort_by){
                case 'create_at':
                    $sort_by = 'create_at.value';
                    break;
                default:
                    $sort_by = 'create_at.value';
                    break;
            }
            $sorted = $orders->sortBy($sort_by, null, $sort_direct );
        } else {
            $sorted = $orders->sortBy('create_at.value', null, $sort_direct );
        }


        $data = [
            "recordsTotal"      => $totalOrders,
            "recordsFiltered"   => $totalOrders,
            "start"             => 0,
            "length"            => 10,
            "data"              => ($limit) ? $sorted->forPage(0, $limit) : $sorted->toArray(),

            'log'               => $this->api2cart->getLog(),
        ];

        return response()->json($data);

    }


    public function orderInfo($store_id=null,$order_id=null,Request $request)
    {
        $order = $this->api2cart->getOrderInfo( $store_id, $order_id );

        if ( $request->ajax() ){
            return response()->json(['data' => view('orders.info',compact('order','store_id', 'order_id'))->render(), 'item' => $order,'log' => $this->api2cart->getLog() ]);
        }

        return redirect( route('orders.index') );
    }

    public function orderProducts($store_id=null,$order_id=null,Request $request)
    {
        $order = $this->api2cart->getOrderInfo( $store_id, $order_id );

        /**
         * get all product's id to featch from 1 request insteed 1 per product
         *

        $pids = [];
        foreach ( $order['order_products'] as $item ){
            $pids[] = $item['product_id'];
        }
        $products = [];
        if (count($pids)){
            $products = $this->api2cart->getProductList( $store_id, $pids );
        }

        */


        if ( $request->ajax() ){
            return response()->json(['data' => view('orders.products',compact('order','store_id', 'order_id'))->render(), 'item' => $order,'log' => $this->api2cart->getLog() ]);
        }

        return redirect( route('orders.index') );

    }

    public function abandoned($store_id=null, Request $request)
    {
        $items = collect( $this->api2cart->getAbandonedCart( $store_id ) );

//        Log::debug( print_r($items,1) );

        $data = [
            "recordsTotal"      => (is_array($items)) ? count($items) : 0,
            "recordsFiltered"   => (is_array($items)) ? count($items) : 0,
            "start"             => 0,
            "length"            => 10,
            "data"              => collect($items),

            'log'               => $this->api2cart->getLog(),
        ];

        return response()->json($data);
    }

    public function statuses($store_id=null, Request $request)
    {
        $statuses = $this->api2cart->getOrderStatuses( $store_id );
        if ( !$statuses ){
            return response()->json(['log' => $this->api2cart->getLog() ], 404);
        }
        if ( $request->ajax() ){
            return response()->json(['data' => collect($statuses['cart_order_statuses']), 'log' => $this->api2cart->getLog() ]);
        }
        return redirect( route('orders.index') );
    }

    public function create(Request $request)
    {
        $carts = collect($this->api2cart->getCartList());

//        Log::debug( print_r($carts,1) );

        if ( $request->ajax() ){
            return response()->json( ['data' => view('orders.form', compact('carts'))->render(), 'item' => $carts ] );
        }
        return redirect( route('orders.index') );
    }

    public function store(OrderRequest $request)
    {
//        Log::debug( print_r($request->all(),1) );

        $cart = $this->api2cart->getCart( $request->get('cart_id') );
        $customer = $this->api2cart->getCustomer( $request->get('cart_id'), $request->get('customer_id') );

        $address = collect( $customer['address_book'] );
        $billing = $address->where('type', 'billing')->first();
        $shipping= $address->where('type', 'shipping')->first();

        // for any case if only shipping avialable
        if ($billing == null) $billing = $shipping;

        // some customers do not have state
        if ( !isset($shipping['state']['code']) || $shipping['state']['code'] == '' ) $shipping['state']['code'] = 'AL';

//        Log::debug( print_r( $address->where('type', 'billing')->first(), 1 ) );
//        Log::debug( print_r($customer,1) );

        $order = [
            'store_id'          => $cart['stores_info'][0]['store_id'],
            'customer_email'    => $customer['email'],
            'order_status'      => $request->get('status_id'),
            'subtotal_price'    => 0,
            'total_price'       => 0,

            'bill_first_name'   => (isset($billing['first_name'])) ? $billing['first_name'] : $shipping['first_name'],
            'bill_last_name'    => (isset($billing['last_name'])) ? $billing['last_name'] : $shipping['last_name'],
            'bill_address_1'    => (isset($billing['address1'])) ? $billing['address1'] : $shipping['address1'],
            'bill_city'         => (isset($billing['city'])) ? $billing['city'] : $shipping['city'],
            'bill_postcode'     => (isset($billing['postcode'])) ? $billing['postcode'] : $shipping['postcode'],

            // state & country need be cleared
            'bill_state'        => (isset($billing['state']['code']) && $billing['state']['code'] != '') ? $billing['state']['code'] : $shipping['state']['code'],
            'bill_country'      => (isset($billing['country']['code3']) && $billing['country']['code3'] != '') ? $billing['country']['code3'] : $shipping['country']['code3'],



        ];

        foreach ($request->get('checked_id') as $cpi){
            $product  = $this->api2cart->getProductInfo( $request->get('cart_id'), $cpi );
            $quantity = $request->get('product_quantity')[ array_search($cpi, $request->get('product_id')) ];

//            Log::debug( print_r($product,1));

            // check if quantity right
            if ( $product['quantity']< $quantity) continue;

            $order['order_item'][] = [
                'order_item_id'         => $product['id'],
                'order_item_name'       => $product['name'],
                'order_item_model'      => $product['u_model'],
                'order_item_price'      => $product['price'],
                'order_item_quantity'   => $quantity
            ];

            $order['subtotal_price']    += $product['price'] * $quantity;
            $order['total_price']       += $product['price'] * $quantity;
        }

        $result = $this->api2cart->createOrder( $request->get('cart_id') , $order );

        if ($result){


            return response()->json([ 'log' => $this->api2cart->getLog(), 'item' => $this->api2cart->getOrderInfo( $request->get('cart_id'), $result['order_id'] ) ]);

        } else {
            // error creating order
            return response()->json([ 'log' => $this->api2cart->getLog() ], 404);
        }


    }

}

src/resources/views/orders/form.blade.php
@if(isset($order_id))
    {!! Form::open(['url' => route('orders.update', [$order_id]) ]) !!}
@else
    {!! Form::open(['url' => route('orders.store') ]) !!}
@endif



<br>
<div class="row text-left">
    <div class="col">

        <div class="alert alert-danger" role="alert" style="display: none;">
            <div id="_form_errors" class="text-left"></div>
        </div>

        <div class="form-group row">
            <label for="name" class="col-4 col-form-label">Store Type</label>
            <div class="col-8">
                <select class="custom-select" id="cart_id" name="cart_id" required >
                    <option selected disabled value="">Choose your cart...</option>
                    @foreach($carts as $item)
                        <option value="{!! $item['store_key'] !!}">{{ $item['cart_id'] }} [ {{ $item['url'] }} ] </option>
                    @endforeach
                </select>
                <div class="invalid-feedback"></div>
            </div>
        </div>

        <div class="form-group row">
            <label for="customer_id" class="col-4 col-form-label">Customer</label>
            <div class="col-8">
                <select class="custom-select" id="customer_id" name="customer_id" required disabled>
                    <option selected disabled value="">Choose customer...</option>
                </select>
                <div class="invalid-feedback"></div>
            </div>
        </div>

        <div class="form-group row">
            <label for="status_id" class="col-4 col-form-label">Order Status</label>
            <div class="col-8">
                <select class="custom-select" id="status_id" name="status_id" required disabled>
                    <option selected disabled value="">Choose status...</option>
                </select>
                <div class="invalid-feedback"></div>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-4 col-form-label">Products</label>
            <div class="col-8" >

                <div class="row" id="productsList" style="max-height: 300px; overflow-y: scroll;">

{{--                    <label class="col-lg-6">--}}
{{--                        <input type="checkbox" name="demo[]" class="card-input-element d-none" value="demo1">--}}
{{--                        <div class="card card-body bg-light d-flex ">--}}
{{--                            <h6>Product name <span class="badge badge-secondary">$10</span></h6>--}}
{{--                            <small>--}}
{{--                                Quantity: <input type="number" min="0" step="1" value="0">--}}
{{--                            </small>--}}
{{--                        </div>--}}
{{--                    </label>--}}


                </div>


            </div>
        </div>

        <div class="form-group row">
            <label for="status_id" class="col-4 col-form-label">Order total</label>
            <div class="col-8">
                <input type="text" class="form-control" id="product_total" name="product_total" value="0" readonly  disabled>
                <div class="invalid-feedback"></div>
            </div>
        </div>

        <div id="addItemFields">
        </div>

    </div>
</div>


{!! Form::close() !!}

src/resources/views/orders/info.blade.php
<br>
<div class="row">
    <div class="col">
        <h3 class="text-left">Shipment address</h3>

        <div class="row text-left">
            <div class="col">{{ $order['customer']['first_name'] }} {{ $order['customer']['last_name'] }}</div>
        </div>
        <div class="row text-left">
            <div class="col">{{ $order['shipping_address']['address1'] }}</div>
        </div>
        @if(isset($order['shipping_address']['address2']))
            <div class="row text-left">
                <div class="col">{{ $order['shipping_address']['address2'] }}</div>
            </div>
        @endif
        <div class="row text-left">
            <div class="col">{{ $order['shipping_address']['city'] }}, {{ (isset($order['shipping_address']['state']['code'])) ? $order['shipping_address']['state']['code'] : '' }} {{ (isset($order['shipping_address']['postcode'])) ? $order['shipping_address']['postcode'] : ''}}</div>
        </div>
        <div class="row text-left">
            <div class="col">{{ (isset($order['shipping_address']['country']['code3'])) ? $order['shipping_address']['country']['code3'] : '' }}</div>
        </div>

    </div>

    <div class="col">
        <h3 class="text-left">Billing address</h3>

        <div class="row text-left">
            <div class="col">{{ $order['customer']['first_name'] }} {{ $order['customer']['last_name'] }}</div>
        </div>
        <div class="row text-left">
            <div class="col">{{ $order['billing_address']['address1'] }}</div>
        </div>
        @if(isset($order['billing_address']['address2']))
            <div class="row text-left">
                <div class="col">{{ $order['billing_address']['address2'] }}</div>
            </div>
        @endif
        <div class="row text-left">
            <div class="col">{{ $order['billing_address']['city'] }}, {{ (isset($order['billing_address']['state']['code'])) ? $order['billing_address']['state']['code'] : '' }} {{ (isset($order['billing_address']['postcode'])) ? $order['billing_address']['postcode'] : ''}}</div>
        </div>
        <div class="row text-left">
            <div class="col">{{ (isset($order['billing_address']['country']['code3'])) ? $order['billing_address']['country']['code3'] : '' }}</div>
        </div>

    </div>

</div>

<div class="row">
    <div class="col"><br></div>
</div>

<div class="row">
    <div class="col">
        <h3 class="text-left">Shipping method</h3>
        <div class="row text-left">
            <div class="col">{{ (isset($order['shipping_method']['name'])) ? $order['shipping_method']['name'] : '' }}</div>
        </div>
    </div>
</div>

src/resources/views/orders/products.blade.php
<br>
@if( isset($order['order_products']) && count($order['order_products']) )
    <div class="row">
        <div class="col">
            <h3 class="text-left">Products:</h3>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Model</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach( $order['order_products'] as $item )
                            <tr>
                                <th>{{ $item['product_id'] }}</th>
                                <td>{{ $item['name'] }}</td>
                                <td>{{ $item['model'] }}</td>
                                <td>{{ $item['price'] }}</td>
                                <td>{{ $item['quantity'] }}</td>
                                <td>{{ $item['total_price'] }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>


        </div>



    </div>
@else
    <h3>No products in this order.</h3>
@endif