src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    return view('welcome');
    return redirect( '/home' );
});

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::middleware(['auth'])->group(function () {
    Route::resource('users', 'UsersController');
});

Route::middleware(['auth', 'apikey'])->group(function () {

    Route::get('/mail_settings', function () {
        return view( 'email_settings' );
    });
    Route::post('/mail_settings', 'HomeController@test')->name('smtp_update');
    Route::get('/test_mail_settings','HomeController@checkSMTP')->name('test_mail_settings');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('stores', 'StoresController');
    Route::any('/stores/list', 'StoresController@storeList')->name('stores.list');
    Route::get('/stores/fields/{id?}', 'StoresController@fields')->name('stores.fields');

    Route::resource('orders', 'OrdersController');
    Route::post('/orders/list/{store_id?}', 'OrdersController@orderList')->name('orders.list');
    Route::post('/orders/statuses/{store_id?}', 'OrdersController@statuses')->name('orders.statuses');
    Route::get('/orders/{store_id?}/{order_id?}', 'OrdersController@orderInfo')->name('orders.info');
    Route::get('/orders/{store_id?}/{order_id?}/products', 'OrdersController@orderProducts')->name('orders.products');
    Route::post('/orders/abandoned/{store_id?}', 'OrdersController@abandoned')->name('orders.abandoned');

    Route::get('/products', 'ProductsController@index')->name('products.index');
    Route::post('/products/list/{store_id?}', 'ProductsController@productList')->name('products.list');
    Route::delete('/products/{store_id?}/{product_id?}', 'ProductsController@destroy')->name('products.delete');
    Route::get('/products/{store_id?}/{product_id?}/edit', 'ProductsController@edit')->name('products.edit');
    Route::post('/products/{store_id?}/{product_id?}', 'ProductsController@update')->name('products.update');
    Route::post('/products/{store_id?}/{product_id?}/delete_image', 'ProductsController@destroyImage')->name('products.deleteImage');

    Route::get('/customers', 'CustomersController@index')->name('customers.index');
    Route::post('/customers/list/{store_id?}', 'CustomersController@customerList')->name('customers.list');
    Route::post('/subscribers/list/{store_id?}', 'CustomersController@subscriberList')->name('subscribers.list');

    Route::get('/categories', 'CategoriesController@index')->name('categories.index');
    Route::post('/categories/list/{store_id?}', 'CategoriesController@categoryList')->name('categories.list');
    Route::get('/categories/{store_id?}/{category_id?}/edit', 'CategoriesController@edit')->name('categories.edit');
    Route::post('/categories/{store_id?}/{category_id?}', 'CategoriesController@update')->name('categories.update');
    Route::delete('/categories/{store_id?}/{category_id?}', 'CategoriesController@destroy')->name('categories.delete');

    Route::any('businessCases', function (){
        return redirect( '/home' );
    });

    Route::prefix('businessCases')
        ->name('businessCases.')
        ->middleware(['checkSMTP'])
        ->group(function () {

        Route::get('import_orders_automation', 'BusinessCases\ImportOrdersAutomationController@index' )->name('import_orders_automation');

        Route::get('automatic_email_sending', 'BusinessCases\AutomaticEmailSendingController@index' )->name('automatic_email_sending');
        Route::post('automatic_email_sending/compose', 'BusinessCases\AutomaticEmailSendingController@compose')->name('automatic_email_sending.compose');
        Route::post('automatic_email_sending/send', 'BusinessCases\AutomaticEmailSendingController@send')->name('automatic_email_sending.send');

        Route::get('abandoned_cart_recovery', 'BusinessCases\AbandonedCartRecoveryController@index' )->name('abandoned_cart_recovery');
        Route::post('abandoned_cart_recovery/compose', 'BusinessCases\AbandonedCartRecoveryController@compose')->name('abandoned_cart_recovery.compose');
        Route::post('abandoned_cart_recovery/send', 'BusinessCases\AbandonedCartRecoveryController@send')->name('abandoned_cart_recovery.send');

        Route::get('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@index")->name('automatic_price_updating');
        Route::get('automatic_price_updating/create', "BusinessCases\AutomaticPriceUpdatingController@create")->name('automatic_price_updating.create');
        Route::get('automatic_price_updating/edit', "BusinessCases\AutomaticPriceUpdatingController@edit")->name('automatic_price_updating.edit');
        Route::post('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@store")->name('automatic_price_updating.store');
        Route::put('automatic_price_updating', "BusinessCases\AutomaticPriceUpdatingController@update")->name('automatic_price_updating.update');
        Route::get('automatic_price_updating/products', "BusinessCases\AutomaticPriceUpdatingController@products")->name('automatic_price_updating.products');

    });



});

src/app/Http/Controllers/StoresController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRequest;
use App\Services\Api2Cart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class StoresController extends Controller
{
    private $api2cart;


    public function __construct(Api2Cart $api2Cart)
    {
        $this->api2cart = $api2Cart;
    }

    public function index()
    {

//        $this->api2cart->test();

        return view('stores.index');
    }


    public function storeList(Request $request)
    {
        \Debugbar::disable();

        /**
         * get account carts & avialable carts
         */
        $carts = collect($this->api2cart->getCartList());
        $allCarts = collect($this->api2cart->getCartsList());

//        Log::debug( print_r($allCarts,1));
//        if ( !$carts->count() || !$allCarts->count() ) return response()->json([],404);


        $result = $carts->map(function ($store) use ($allCarts) {
            $info = $this->api2cart->getCart( $store['store_key'] );
            // put additional info
            $store['stores_info']['store_owner_info']   = [
                'owner' => ( isset($info['stores_info'][0]['store_owner_info']['owner']) ) ? $info['stores_info'][0]['store_owner_info']['owner'] : null,
                'email' => ( isset($info['stores_info'][0]['store_owner_info']['email']) ) ? $info['stores_info'][0]['store_owner_info']['email'] : null
            ];
            $store['cart_info']     = $allCarts->where('cart_id', $store['cart_id'])->first();
            return $store;
        });

        $data = [
            "recordsTotal"      => $result->count(),
            "recordsFiltered"   => $result->count(),
            "start"             => 0,
            "data"              => $result,

            'log'               => $this->api2cart->getLog(),
        ];

        return response()->json($data);
    }

    public function fields(Request $request, $id=null)
    {
        $store = collect($this->api2cart->getCartsList())->where('cart_id',$id)->first();

//        Log::debug( print_r($store,1) );

//        return '';

        return view('stores.store_fields', compact('store'));

    }


    public function create(Request $request)
    {
        // get supported carts
        $stores = collect($this->api2cart->getCartsList());
//            ->whereIn('cart_id',['Amazon']);


//        Log::debug( print_r($stores,1) );



        if ( $request->ajax() ){
            return response()->json( ['data' => view('stores.form', compact('stores'))->render(), 'item' => $stores ] );
        }
        return redirect( route('stores.index') );
    }


    public function store(StoreRequest $request)
    {
//        Log::debug( $request->all() );
        //load required store info
        $store = collect($this->api2cart->getCartsList())->where('cart_id',$request->get('cart_id'))->first();

        $requestData = $request->except(['_token']);
        $requestData['field']['cart_id'] = $request->get('cart_id');

        $fields = (isset($requestData['custom'])) ? array_merge( $requestData['field'], $requestData['custom'] ) : $requestData['field'];

        $result = $this->api2cart->addCart( $fields );


        if ( $request->ajax() ){

            Log::debug( print_r($result,1));

            if ( intval($result['return_code']) == 0 )  {
                return response()->json( ['data' => $result, 'log' => $this->api2cart->getLog() ] );
            } else {
                return response()->json( ['msg' => $result['return_message'], 'log' => $this->api2cart->getLog() ] , 404 );
            }
        }

        return redirect( route('stores.index') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id=null)
    {
        if ( $this->api2cart->deleteCart( $id ) ){
            return response()->json([ 'log' => $this->api2cart->getLog() ]);
        } else {
            return response()->json([ 'log' => $this->api2cart->getLog() ], 404);
        }

    }

}

src/resources/views/stores/form.blade.php
@if(isset($store_id))
    {!! Form::open(['url' => route('stores.update', [$store_id]) ]) !!}
@else
    {!! Form::open(['url' => route('stores.store') ]) !!}
@endif



<br>
<div class="row text-left">
    <div class="col">

        <div class="alert alert-danger" role="alert" style="display: none;">
            <div id="_form_errors" class="text-left"></div>
        </div>

        <div class="form-group row">
            <label for="name" class="col-4 col-form-label">Store Type</label>
            <div class="col-8">
                <select class="custom-select" id="cart_id" name="cart_id" required >
                    <option selected disabled value="">Choose your cart...</option>
                    @foreach($stores as $store)
                    <option value="{!! $store['cart_id'] !!}">{{ $store['cart_name'] }}</option>
                    @endforeach
                </select>
                <div class="invalid-feedback"></div>
            </div>
        </div>


        <div id="addItemFields">
        </div>

    </div>
</div>


{!! Form::close() !!}

src/resources/views/stores/index.blade.php
@extends('layouts.app')

@section('script')
    <script type="text/javascript">
        let selectItems = [];

        function loadData(){

            blockUiStyled('<h4>Loading stores information.</h4>');

            stores = [];


            return axios({
                method: 'post',
                url: '{{ route('stores.list') }}',
                data: {
                    length: 10,
                    start: 0
                }
            }).then(function (response) {

                stores = response.data.data;

                if ( response.data.log ){
                    for (let k=0; k<response.data.log.length; k++){
                        logItems.push( response.data.log[k] );
                    }
                    calculateLog();
                }

                if ( !stores.length ){
                    Swal.fire({
                        title: 'Info',
                        text: 'Do not have store info, please check API log or Add stores.',
                        icon: 'info',

                        buttonsStyling: false,
                        confirmButtonClass: 'btn btn-primary btn-lg',
                        cancelButtonClass: 'btn btn-lg',
                    })
                }

                var datatable = $( '#dtable' ).dataTable().api();

                datatable.clear();
                datatable.rows.add( stores );
                datatable.draw();

                $.unblockUI();

                reinitActions();
                $.growlUI('Notification',  ' data loaded successfull!', 500 );
                initFilters();

            }).catch(function (error) {
                // handle error
                // console.log(error.response);

                if ( error.response.data.log ){
                    for (let k=0; k<error.response.data.log.length; k++){
                        logItems.push( error.response.data.log[k] );
                    }
                    calculateLog();
                }

                $.unblockUI();

                Swal.fire({
                    title: 'Error!',
                    text: 'Do not have store info, please check API log.',
                    icon: 'error',

                    buttonsStyling: false,
                    confirmButtonClass: 'btn btn-primary btn-lg',
                    cancelButtonClass: 'btn btn-lg',
                })

            });

        }


        function addStore()
        {
            let action = "{{ route('stores.create') }}";

            axios.get( action )
                .then(function (response) {
                    // handle success
                    // console.log(response);

                    selectItems = response.data.item;

                    Swal.fire({
                        title: 'Add new Store',
                        html: response.data.data,
                        customClass: {
                            confirmButton: 'btn btn-primary',
                            cancelButton: 'btn btn-danger'
                        },
                        showCancelButton: true,
                        showCloseButton: true,
                        buttonsStyling: false,
                        confirmButtonText: 'Create',
                        width: '70%',
                        allowOutsideClick: false,
                        preConfirm: ( pconfirm ) => {

                            $('.swal2-content').find('.is-invalid').removeClass('is-invalid');

                            let fact = $('.swal2-content form')[0].action;
                            var formData = getFormData( $('.swal2-content form') );


                            return axios.post( fact , formData , {
                                headers: {
                                    'Content-Type': 'multipart/form-data'
                                }
                            })
                                .then(function (presponse) {

                                    Swal.fire(
                                        'Added!',
                                        'Store has been added.',
                                        'success'
                                    ).then((result) => {
                                        window.location.reload();
                                    });

                                    return true;
                                })
                                .catch(function (error) {

                                    // console.log( error.response.data );

                                    if ( typeof error.response.data.errors != 'undefined'){

                                        $.each(error.response.data.errors, function(index, value) {
                                            let obj = $( document.getElementById(index) );
                                            let err = $(obj).parent().parent().find('.invalid-feedback');
                                            $(err).empty().append( value.shift() );
                                            $(obj).addClass('is-invalid');
                                        });

                                    }

                                    if ( typeof error.response.data.msg != 'undefined'){
                                        let obj = document.getElementById( 'field.store_url' );
                                        let err = $(obj).parent().parent().find('.invalid-feedback');
                                        $(err).empty().append( error.response.data.msg );
                                        $(obj).addClass('is-invalid');
                                        $('#_form_errors').empty().append( error.response.data.msg );
                                        $('#_form_errors').parent().show().fadeOut(9000);
                                    }


                                    return false;
                                });


                        },
                    });



                    $('#cart_id').change(function(e){

                        let selected = this.value;



                        let item = Object.values( selectItems ).find( obj =>{ return obj.cart_id === selected } );
                        $('#addItemFields').empty();

                        axios.get( 'stores/fields/' + item.cart_id ).then(function (cfresponse) {
                            $('#addItemFields').append( cfresponse.data );
                        });
                    });



                    //update log count
                    if ( response.data.log ){
                        for (let k=0; k<response.data.log.length; k++){
                            logItems.push( response.data.log[k] );
                        }
                        calculateLog();
                    }
                    $.unblockUI();

                })
                .catch(function (error) {
                    // handle error
                    console.log(error);
                    $.unblockUI();


                    Swal.fire({
                        title: 'Error!',
                        text: 'Failed info ' + id,
                        icon: 'error',

                        buttonsStyling: false,
                        confirmButtonClass: 'btn btn-primary btn-lg',
                        cancelButtonClass: 'btn btn-lg',
                    })

                });
        }


        function initFilters()
        {
            var names = getUniqueName();
            var owner = getUniqueOwner();
            var store = getUniqueStore();


            yadcf.init( table , [
                {
                    column_number: 1,
                    select_type: 'select2',
                    data: names,
                    select_type_options: { width: '200px' }
                },
                {
                    column_number: 2,
                    select_type: 'select2',
                    data: owner,
                    select_type_options: { width: '200px' }
                },
                {
                    column_number: 0,
                    select_type: 'select2',
                    data: store,
                    select_type_options: { width: '200px' }
                },

            ]);

        }


        function getUniqueName()
        {
            var uniqueItem = [];
            stores.filter(function(item){
                let name = item.cart_info.cart_name
                if (!~uniqueItem.indexOf(name)) {
                    uniqueItem.push(name);
                    return item;
                }
            });
            return uniqueItem;
        }

        function getUniqueOwner()
        {
            var uniqueItem = [];
            stores.filter(function(item){
                let owner = (item.stores_info.store_owner_info.owner) ? item.stores_info.store_owner_info.owner : '';
                if (!~uniqueItem.indexOf(owner)) {
                    uniqueItem.push(owner);
                    return item;
                }
            });
            return uniqueItem;
        }

        function getUniqueStore()
        {
            var uniqueItem = [];
            stores.filter(function(item){
                let url = (item.url) ? item.url : '';
                if (!~uniqueItem.indexOf(url)) {
                    uniqueItem.push(url);
                    return item;
                }
            });
            return uniqueItem;
        }




        var table;


        $(document).ready(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });



            loadData();
            // $.unblockUI();

            table = $('#dtable').DataTable( {
                processing: true,
                // serverSide: true,
                // ordering: false,
                data: stores,
                // dom: 'B<lf<t>ip>',
                dom: '<"row"<"col"B><"col"l><"col"f>><t><"row"<"col"i><"col">p>',
                buttons: [
                    {
                        text: 'Reload',
                        action: function ( e, dt, node, config ) {
                            window.location.reload();
                        },
                        className: 'btn btn-primary'
                    },
                    {
                        text: 'Add Store',
                        action: function ( e, dt, node, config ) {

                            addStore();

                        },
                        className: 'btn btn-primary'
                    }
                ],
                language: {
                    emptyTable: "Data loading or not available in table"
                },
                initComplete: function () {
                    $('#dtable_filter input').focus();
                },
                columns: [
                    { data: null, render: function ( data, type, row, meta ){
                            return '<a href="'+data.url+'">'+data.url+'</a><br><small>'+data.store_key+'</small>';
                    } },
                    { data: null, render: function ( data, type, row, meta ){
                        let imgName = data.cart_info.cart_name.toLowerCase().replace(/ /g,"_");
                        return '<img class="cartImage" src="https://api2cart.com/wp-content/themes/api2cart/images/logos/'+imgName+'.png"><br>' +
                        data.cart_info.cart_name+'<br><small>'+data.cart_info.cart_versions+'</small>';
                    }  },
                    { data: null, render: function ( data, type, row, meta ){

                            return data.stores_info.store_owner_info.owner+'<br><small>'+data.stores_info.store_owner_info.email+'</small>';

                        }  },
                    {
                        data: null, render: function ( data, type, row, meta ){
                            // return '<i class="far fa-file-alt"></i> ' +
                            //     '<i class="fas fa-edit"></i> ' +
                                return '<a href="#"  class="text-danger deleteItem" data-id="'+data.id+'" data-name="'+data.url+'" data-action="/stores/'+data.store_key+'"><i class="fas fa-trash-alt"></i></a> ';
                        }, orderable : false
                    }
                ],
                "drawCallback": function( settings ) {
                    reinitActions();
                }
            } );


        } );
    </script>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            @include('parts.sidebar')

            <div class="col-lg-10">
                <div class="card">
                    <div class="card-header">Stores <span class="ajax_status"></span>
                        <span class="float-right"><a target="_blank" href="https://docs.api2cart.com/post/interactive-docs?version=v1.1#operations-tag-cart">Read Carts API methods</a></span>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col text-right api_log">
                                <a href="#" id="showApiLog" >Performed <span>0</span> requests with API2Cart. Click to see details...</a><br>
                            </div>
                        </div>
                        <table id="dtable" class="table table-bordered" style="width:100%">
                            <thead>
                            <tr>
                                <th>Store</th>
                                <th>Cart Type</th>
                                <th>Store Owner</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/resources/views/stores/store_fields.blade.php
@php
    $required     = collect( $store['params']['required'][0] );
    $custom     = collect( $store['params']['additional'] );
@endphp

@foreach( $required->whereNotIn('name',['cart_id']) as $k=>$v )
<div class="form-group row">
    <label for="field.{{$v['name']}}" class="col-4 col-form-label">{{ $v['name'] }}</label>
    <div class="col-8">
        <input type="text" class="form-control" id="field.{{$v['name']}}" name="field[{{ $v['name'] }}]" value="">
        <small id="emailHelp" class="form-text text-muted">{{ $v['description'] }}</small>
        <div class="invalid-feedback"></div>
    </div>
</div>
@endforeach

@if( count($custom) > 0 )

    <div class="form-group row">
        <label for="verify" class="col-4 col-form-label"></label>
        <div class="col-8">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="verify" name="field[verify]" value="false">
                <label class="custom-control-label" for="verify">Skip verification</label>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="verify" class="col-4 col-form-label"></label>
        <div class="col-8">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="use_additional" name="use_additional" data-toggle="collapse" data-target="#collapseExample" >
                <label class="custom-control-label" for="use_additional">Use additional params</label>
            </div>
        </div>
    </div>



    <div class="collapse" id="collapseExample">
        @foreach( $custom->whereNotIn('name',['verify']) as $item )
            <div class="form-group row">
                <label for="custom.{{$item['name']}}" class="col-4 col-form-label">{{ $item['name'] }}</label>
                <div class="col-8">
                    <input type="text" class="form-control" id="custom.{{$item['name']}}" name="custom[{{ $item['name'] }}]" value="">
                    <small id="{{$item['name']}}.Help" class="form-text text-muted">{{ $item['description'] }}</small>
                    <div class="invalid-feedback"></div>
                </div>
            </div>
        @endforeach
    </div>


@endif